alias desk="cd ~/Desktop"
alias ll="ls -lhF"
alias la="ls -lAhF"
alias lr="ls -lhFR"
alias lar="ls -lhFaR"
alias gzip="gzip -9"
alias bzip2="bzip2 -9"
alias ztar="tar czvf"
alias jtar="tar cjvf"
alias xztar="tar xzvf"
alias xjtar="tar xjvf"
alias cp="cp -i"
alias mv="mv -i"

#alias cp="cp -p" #Cause cp to preserve the following attributes of each source file in the copy: modification time, access time, file flags, file mode, user ID, and group ID, as allowed by permissions.

alias jirafy="/usr/local/www/support/jirafy.sh"
alias mvc="/usr/local/www/support/mvc.sh"
alias create_ticket="/usr/local/www/support/create_ticket.sh"

alias bgrep="/usr/local/www/utils/bgrep.sh"
alias bfind="/usr/local/www/utils/bfind.sh"
alias brm="/usr/local/www/utils/brm.sh"
alias barchiver="python3 /usr/local/www/utils/barchiver.py"

alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."
alias ..6="cd ../../../../../.."
alias ..7="cd ../../../../../../.."
alias ..8="cd ../../../../../../../.."
alias ..9="cd ../../../../../../../../.."
alias ..l="cd .. && ll"
alias :q="exit"

# debian
alias sapt="apt-cache search"
alias iapt="sudo apt-get install"
alias papt="sudo apt-get purge"
