#!/bin/bash

set -euo pipefail

LANG=C
umask 0022

ERROR="\e[31m[ERROR]\e[0m"
INFO="\e[34m[INFO]\e[0m"
SUCCESS="\e[32m[SUCCESS]\e[0m"

if [ $EUID -ne 0 ]
then
    printf "%b This script must be run as root!\n" "$ERROR" 1>&2
    exit 1
fi

trap cleanup EXIT

cleanup() {
    rm -rf foo
}

BINS=(
    virsh
    virt-install
)

for bin in "${BINS[@]}"
do
    if ! command -v "$bin" > /dev/null
    then
        printf "%b \`%s\` not found in PATH.\n" "$ERROR" "$bin"
        exit 1
    fi
done

SCRIPTNAME=$(basename "$0")

usage() {
    printf "Usage: %s OPTIONS

Options:
--cidr=         Provide the bridge network address (defaults to 172.16.0.1/12).
--destroy, -d   Delete the network namespace(s) and the bridge.
 -n=            The number of containers to create (defaults to one).
--ns=           The name of the net namespace to be created (defaults to netns).
--step=         Increase the value of the IP address by STEP (defaults to 1).
--verbose, -v   Verbose mode.
--help, -h      Help.\n" "$SCRIPTNAME"
    exit "$1"
}

while [ "$#" -gt 0 ]
do
    OPT="$1"
    case $OPT in
        -c|--cluster) shift ; CLUSTER=$1 ;;
        --dry-run) DRY_RUN=true ;;
        -p|--profile) shift ; PROFILE=$1 ;;
        -h|--help) usage 0 ;;
        *) printf "Unknown flag %s\n" "$OPT"; usage 1 ;;
    esac
    shift
done

