# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "vagrant-HOSTNAME.local"

    # `host_ip` binds the port to the lo interface on the host (no remote access).
#    config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1
#    config.vm.network "private_network", ip: "192.168.33.10"
#    config.vm.network "public_network", ip: "192.168.1.53", bridge: "wlp3s0"

    config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ["vers=3,tcp"]
    config.ssh.forward_agent = true

    config.vm.provider "libvirt" do |lv|
        lv.cpus = 4
        lv.memory = 8192
    end

    config.vm.provision :shell, run: "always", inline: "systemctl restart systemd-timesyncd.service"

#    config.vm.provision :shell do |s|
#        s.path = "scripts/root.sh"
#        s.env = {
#            USER:ENV["USER"],
#        }
#    end

    config.vm.provision :shell, inline: <<-SHELL
        apt-get update && \
        apt-get install -y \
            build-essential \
            curl \
            git \
            gnupg2 \
            wget

        # Fixes the "-bash: warning: setlocale: LC_ALL: cannot change locale (en_IN.UTF-8)" warning.
        # Also, fixes the same warnings for Perl.
        localedef -i en_US -f UTF-8 en_US.UTF-8
    SHELL

    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        touch "$HOME/.hushlogin"
        # lastlog -u $USER
    SHELL

    config.vm.provision :ansible_local do |ansible|
        ansible.become = true
        ansible.groups = {
            "servers" => ["default"]
        }
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "ansible/playbook.yml"
        ansible.version = "latest"
        ansible.extra_vars = {
            ansible_python_interpreter: "/usr/bin/python3"
        }
        ansible.galaxy_roles_path = nil
        ansible.galaxy_role_file = "ansible/requirements.yml"
        ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}"
    end
end

